name: Build Sphinx Docs

on:
  release:
    types: [published]
    # Paths to watch for triggering the workflow
    paths:
      - 'jef/**'
      - 'docs/**'
      - '.github/workflows/api-docs.yml'

  # allow manual triggering
  workflow_dispatch:

jobs:
  build-docs:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install sphinx sphinx_rtd_theme sphinx-autodoc-typehints

    - name: Update RST files
      run: |
        cd docs
        rm -rf source/api
        mkdir -p source/api
    
        sphinx-apidoc -f -o source/api ../jef \
         --separate \
         --module-first \
         --implicit-namespaces

        echo "Generated API documentation files:"
        ls -la source/api/
        cd ..


    - name: Build documentation
      run: |
        sphinx-build -b html docs/source docs/build/html