name: Build Sphinx Docs

on:
  # allow manual triggering
  workflow_dispatch:

jobs:
  check-team-permission:
    name: Check team permissions
    runs-on: ubuntu-latest
    # Only run this job for workflow_dispatch events
    if: github.event_name == 'workflow_dispatch'
    steps:
      - name: Check team membership
        id: check-team
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.TEAM_ACCESS_TOKEN }}
          script: |
            const actor = context.actor;
            const org = context.repo.owner;
            const teamSlug = '0din-developers'; // Replace with your actual team slug name

            console.log(`Checking if ${actor} belongs to ${teamSlug} team`);

            try {
              const { status } = await github.request('GET /orgs/{org}/teams/{team_slug}/memberships/{username}', {
                org: org,
                team_slug: teamSlug,
                username: actor
              });

              if (status === 200) {
                console.log(`${actor} is a member of ${teamSlug} team`);
                return true;
              }
            } catch (error) {
              if (error.status === 404) {
                core.setFailed(`User ${actor} is not a member of the ${teamSlug} team and is not authorized to manually trigger this workflow.`);
              } else {
                core.setFailed(`Error checking team membership: ${error.message}`);
              }
              return false;
            }
  

  build-docs:
    runs-on: ubuntu-latest
    if: |
      github.event_name != 'workflow_dispatch' || 
      (github.event_name == 'workflow_dispatch' && success())


    permissions:
      contents: write

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install 0din-jef sphinx sphinx_rtd_theme sphinx-autodoc-typehints furo

    - name: Update RST files
      run: |
        cd docs
        rm -rf source/api
        mkdir -p source/api
    
        sphinx-apidoc -f -o source/api ../jef \
         --separate \
         --module-first \
         --implicit-namespaces

        echo "Generated API documentation files:"
        ls -la source/api/
        cd ..


    - name: Build documentation
      run: |
        sphinx-build -b html docs/source docs/build/html

    - name: Deploy to GitHub Pages
      if: github.event_name == 'workflow_dispatch' || github.event_name == 'release'
      uses: peaceiris/actions-gh-pages@v3
      with:
        personal_token: ${{ secrets.GH_PAGES_TOKEN }}
        publish_dir: ./docs/build/html


